### ISSUE TITLE
[Bug]: Change light mode UI

### ISSUE THREAD

**Issue by shreyansh1410** [vigneshs-dev/golang-to-do-app#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In light mode, when all tasks are done, the text "All tasks completed" becomes invisible due to UI colour scheme

### Add ScreenShots

![image](https://github.com/user-attachments/assets/5ecfd083-ce4c-4d1a-94fa-1d282e5f3fed)
![image](https://github.com/user-attachments/assets/7e37c342-f5b5-4689-a8d3-7a5a0998891c)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vigneshs-dev** [comment]
Sure @shreyansh1410 . I assign this task to you. You can start working on this issue. Thankyou for your contribution.
