### ISSUE TITLE
[Feature Request]: Add Go a Linter in CI

### ISSUE THREAD

**Issue by Pradumnasaraf** [vigneshs-dev/golang-to-do-app#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a Go linter to  analyzes incoming source code for errors, bugs, and other issues

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

**Comment by vigneshs-dev** [comment]
You can start working on this issue. If you are able to create docker container, If you have extra time for that, Please work on that also.

**Comment by Pradumnasaraf** [comment]
I have raised the PR. 

Sorry, I didn't get the Docker container thing you are saying. Yes, I can do that. But someone is already working on that correct?
